### ISSUE TITLE
The values of kernel K in BBFM3D differs from that in MATLAB

### ISSUE THREAD

**Issue by vktsn0303** [ruoxi-wang/BBFMM3D#4]
Hello Ruoxi Wang,

I've been trying to use the BBFMM3D code in C++ and I have been trying to validate it using a simple code written in MATLAB to calculate the same 1./r kernel. At line number 679 of compute.hpp I have written a `cout` statement to be able to see what the values are in the kernel (`cout << *Kij << endl;`). It is oberved that the values of K from the BBFMM3D code are completely different from the one obtained in MATLAB. However, the final result of K*q is approximately correct. I would just like to know if I'm accessing Kij in the `cout` statement correctly or if the actual value of K is calculated somewhere else in the code. Can you please help me understand this?

Many thanks,
vktsn0303

**Comment by ruoxi-wang** [comment]
Hi,

The BBFMM3D code does not form the entire matrix explicitly, otherwise, it
will fall back to an O(n^2) method. Instead, it factorizes the matrix in a
hierarchical fashion and returns an operator that can be applied to a
vector in O(n) complexity. You can refer to the paper titled "The black-box
fast multipole method" for detailed information.  The code in line 679 used
the variable name Kij but it is not the exact entry in your matrix. If you
want to see what the approximated matrix is like, you can apply the
operator to an identity matrix.

I hope this helps.

**Comment by vktsn0303** [comment]
Hi,

Thank you very much for that explanation. I can see what you mean. 

vktsn0303
